name: Selenium Test Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  selenium-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Selenium script
      run: xvfb-run python script.py

    - name: Upload screenshots
      if: always()  # Ensure this runs even if the script fails
      uses: actions/upload-artifact@v3
      with:
        name: screenshots
        path: screenshots/  # Path to the folder containing screenshots
